{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "risk-platform.fullname" . }}
  labels:
    {{- include "risk-platform.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts: [{{ .Values.ingress.host | quote }}]
      secretName: {{ .Values.ingress.tlsSecretName }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "risk-platform.fullname" . }}-risk-admin
                port: {number: 8083}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "risk-platform.fullname" . }}-risk-console
                port: {number: {{ (index .Values.components "risk-console").port }}}
{{- end }}
