<script setup lang="ts">
import { ref, watch } from 'vue'; import { useRoute, useRouter } from 'vue-router'; import { ElMessage, ElMessageBox } from 'element-plus'; import PageState from '../components/PageState.vue'; import RiskBadge from '../components/RiskBadge.vue'; import { api } from '../services/api'; import { useResource } from '../composables/useResource'; import type { Decision, PageResponse } from '../types'; import { useAuthStore } from '../stores/auth'
const auth=useAuthStore(); const route=useRoute(); const router=useRouter(); const level=ref(''); const txn=ref(''); const selected=ref<Record<string,unknown>|null>(null); const drawer=ref(false)
const resource=useResource(()=>{ const params=new URLSearchParams({size:'50'}); if(level.value) params.set('riskLevel',level.value); if(txn.value.trim()) params.set('q',txn.value.trim()); return api<PageResponse<Decision>>(`/api/v1/decisions?${params}`) })
function search(){ router.replace({path:'/decisions',query:txn.value.trim()?{q:txn.value.trim()}: {}}) }
async function detail(id:string){ selected.value=await api<Record<string,unknown>>(`/api/v1/decisions/${id}`);drawer.value=true }
async function replay(id:string){ const {value}=await ElMessageBox.prompt('说明重放原因，原事件不会被修改。','授权重放',{inputPattern:/.{3,}/,inputErrorMessage:'至少输入 3 个字符',confirmButtonText:'创建重放',cancelButtonText:'取消'});await api(`/api/v1/decisions/${id}/replay`,{method:'POST',body:JSON.stringify({reason:value})});ElMessage.success('已创建新的审计重放事件') }
watch(()=>route.query.q,(value)=>{txn.value=typeof value==='string'?value:''; resource.load()},{immediate:true})
</script>
<template><div><header class="page-title"><div><h2>风险决策</h2><p>检索决策快照，核对规则与模型版本</p></div></header><article class="panel"><form class="toolbar" @submit.prevent="search"><el-input v-model="txn" clearable placeholder="精确输入交易流水" style="width:240px" aria-label="交易流水筛选"/><el-select v-model="level" clearable placeholder="全部风险等级" style="width:180px" @change="resource.load"><el-option v-for="item in ['LOW','MEDIUM','HIGH','REJECT']" :key="item" :label="item" :value="item"/></el-select><el-button type="primary" native-type="submit">搜索</el-button><el-button @click="resource.load">刷新</el-button><span class="spacer mono">TOTAL {{ resource.data.value?.total ?? 0 }}</span></form><PageState :loading="resource.loading.value" :error="resource.error.value" :empty="resource.data.value?.content.length===0" @retry="resource.load"><el-table v-if="resource.data.value" :data="resource.data.value.content" @row-click="(row:Decision)=>detail(row.decisionId)"><el-table-column prop="txnId" label="交易流水" min-width="170"><template #default="scope"><span class="mono">{{ scope.row.txnId }}</span></template></el-table-column><el-table-column prop="sourceId" label="来源"/><el-table-column label="等级" width="110"><template #default="scope"><RiskBadge :level="scope.row.riskLevel"/></template></el-table-column><el-table-column prop="action" label="动作"/><el-table-column prop="fraudScore" label="模型分"><template #default="scope">{{ Number(scope.row.fraudScore).toFixed(3) }}</template></el-table-column><el-table-column prop="costMs" label="耗时"><template #default="scope">{{ scope.row.costMs }} ms</template></el-table-column><el-table-column prop="createdAt" label="决策时间" min-width="170"/></el-table></PageState></article><el-drawer v-model="drawer" title="决策证据快照" size="min(560px, 94vw)"><div v-if="selected" class="detail-stack"><div class="key-values"><div v-for="(value,key) in selected" :key="key"><label>{{ key }}</label><span class="mono">{{ value }}</span></div></div><el-button v-if="auth.can('decision.replay')" type="warning" plain @click="replay(String(selected.decision_id ?? selected.decisionId))">授权重放</el-button></div></el-drawer></div></template>
