server:
  port: 8084
spring:
  profiles:
    default: dev
  application:
    name: fraud-decision-log
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    consumer:
      group-id: fraud-decision-log-v1
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
risk:
  elasticsearch:
    base-url: ${ES_URL:http://localhost:9200}
    decision-index: ${DECISION_INDEX:risk-decisions-v1}
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
